# Services

SERVICE_BUS = 'bus'
SERVICE_JOBS = 'jobs'
SERVICE_QUEUE = 'queue'

# Message types.

MT_QUEUE_POKE = 'queue:poke'
MT_QUEUE_TASK_SUCCESS = 'queue:task_success'
MT_QUEUE_TASK_FAILED = 'queue:task_failed'

# Job fields

JF_TIME_ABSOLUTE_OBJ = 'RUN_AT_ABSOLUTE_OBJ'
JF_TIME_TIME_OBJ = 'RUN_AT_TIME_OBJ'
JF_TIME_INTERVAL_S = 'RUN_AT_INTERVAL_S'
JF_ROUTINE = 'RUN_ROUTINE'
JF_EMAIL_SUCCESS_EMAIL_LIST = 'RUN_SUCCESS_EMAIL_LIST'
JF_EMAIL_FAIL_EMAIL_LIST = 'RUN_FAIL_EMAIL_LIST'
