#!/usr/bin/env python2.7

import sys
import os
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import scheduler.config.log
import scheduler.reactor

r = scheduler.reactor.Reactor()
r.run()
